### ISSUE TITLE
Gas price configuration

### ISSUE THREAD

**Issue by giskook** [okx/xlayer-erigon#165]
Check gas price configuration. check whether or not the gas price follow the L1's
Our gas price is 0.01x with L1's gas price, should consider ETH/OKB

**Comment by Vui-Chee** [comment]
Link to gas price doc is [here](https://okg-block.larksuite.com/wiki/WG26wUwkhiqhD8kwFGIuevOFsRg).

**Comment by giskook** [comment]
https://github.com/0xPolygonHermez/cdk-erigon/issues/1538
