### ISSUE TITLE
Research on proxyd

### ISSUE THREAD

**Issue by giskook** [okx/xlayer-erigon#176]
1. For  `consensus_aware` routing_strategy, how can we configure redis, to make multi proxyd instances with the same height.
```
[backend_groups.erigon_out]
backends = ["eg-2", "eg-1", "eg-0"]
routing_strategy = "consensus_aware"
consensus_poller_interval = "100ms"
```
2. Research on different routing_strategy
3. Once backend service restarts, can the requests handled by other backends? the retry mechanism

**Comment by Vui-Chee** [comment]
1. proxyd supports HA Redis consensus mechanism which synchronizes state across multiple proxyd instances using Redis. This only works if all proxyd instances govern the same backend group.
2. There are to my knowledge only 2 types of routing, first is blind forwarding, and the second is multicall forwarding. In the former, a healthy backend is randomly selected to forward request, and in the latter, the request is forwarded to all backends and the first successful response is returned. `consensus_aware` only means the requests will be rewritten with consensus state (safe, finalized block number etc.), and has no bearing on which backend the request will be sent to.
3. Yes. The request is forwarded to the backend group. Proxyd sends the request to the backend and retries X times. If there is no successful response from the current backend, it will attempt the same request to the next backend, and so on and so forth. The ordering of the healthy backends is random.
