### ISSUE TITLE
Research the reason why the Rpc block num bigger than Seq's

### ISSUE THREAD

**Issue by zjg555543** [okx/xlayer-erigon#184]
Normally, the block height of RPC should be lower than that Seq.
In fact, there always appare inversely, especially in devnet.

**Test result**
Private network:
```
[block] rpc: 2498, seq: 2497, diff: -1
```
**The devnet.**
```
[block] rpc: 79307, seq: 79229, diff: -78
```

**Reproduce**
```
#private network
make build-docker; 
cd test
make run
```
https://github.com/zjg555543/xlayer-tools
python3 diff_rpc_seq.py

**Comment by Vui-Chee** [comment]
I believe this PR https://github.com/0xPolygonHermez/cdk-erigon/pull/1527 fixes the issue. Ran locally built from our dev branch. 
<img width="1080" alt="Screenshot 2024-12-03 at 10 11 57 AM" src="https://github.com/user-attachments/assets/c29a8d55-e517-482b-b96c-be1998475b55">

**Comment by Vui-Chee** [comment]
This will be closed by https://github.com/0xPolygonHermez/cdk-erigon/pull/1527.
