### ISSUE TITLE
OOM while stressing test on RPC & Sequencer 

### ISSUE THREAD

**Issue by zjg555543** [okx/xlayer-erigon#185]
- Devnet
- 8C 16 G

After stressing test for a long time, they both got an oom issue.
```
Last state: Terminated with 137: OOMKilled, started: Fri, Nov 29 2024 5:16:36 am, finished: Fri, Nov 29 2024 9:44:32 am
```

**Comment by zjg555543** [comment]
RPC will panic while have a mismatch panic.
https://github.com/okx/xlayer-erigon/blob/upstream/v2.60.0-RC4/zk/stages/stage_interhashes.go#L174

**Comment by zjg555543** [comment]
**Sequencer**
OOM or Too low memory? 
maybe OOM sometimes, seams the `StartAsyncVerification ` use so much memory 
[current.heap.zip](https://github.com/user-attachments/files/17974601/current.heap.zip)

**Comment by zjg555543** [comment]
> Currently We have 4 vCPU and 16GB of memory for erigon-sequencer

Our machine is 16G now, without any stress test.
Could you help check the pprof? - pprof file: [current.heap.zip](https://github.com/user-attachments/files/17974601/current.heap.zip)

**Comment by obynonwane** [comment]
In regard  this, looks like you are also sending the full witness.  Do you have `zkevm.witness-full: false` set?

**Comment by zjg555543** [comment]
Yes, I set the `zkevm.witness-full: true`.

I found that if `zkevm.witness-full` is set to `true`, it results in an OOM within half an hour. Conversely, when set to `false`, the memory usage remains relatively stable for up to two hours.

**Comment by zjg555543** [comment]
What's meanning of `zkevm.witness-full=true`
Is it for aggregator?
Should we always set  false with the Sequencer and RPC on the production chain ?

**Comment by obynonwane** [comment]
`zkevm.witness-full`,  Controls whether the full or partial witness is used with the executor.

**Comment by zjg555543** [comment]
> `zkevm.witness-full`, Controls whether the full or partial witness is used with the executor.

@obynonwane https://github.com/okx/xlayer-erigon/issues/194 The agg cost 70s to get witness, is it okay?
